version: '3.0'
services:
  app:
    build: .
    container_name: app
    tty: true
    working_dir: /var/www
    ports:
      - "8001:8000"
    volumes:
      - ./shop-api:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./shop-api:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - app-network

  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
