version: '3.0'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    tty: true
    ports:
      - "3307:3306"
    environment:
      - MYSQL_MULTIPLE_DATABASES=shop,shop-test
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./.docker/mysql-database.sh:/docker-entrypoint-initdb.d/mysql-database.sh
    networks:
      - app-network

  app:
    depends_on:
      - mysql-db
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      - COMPOSER_INSTALL=DISABLE
      - NPM_INSTALL=DISABLE
      - DB_SEED=DISABLE
